#!/bin/bash

sh run.sh ${FORWARD} ${REVERSE} ${GRAFTM_PACKAGE} ${DECOY_DATABASE} ${EXPAND_SEARCH_CONTIGS} ${SEARCH_HMM_FILES} ${SEARCH_DIAMOND_FILE} ${ALN_HMM_FILE} ${EUK_HMM_FILE} ${INPUT_SEQUENCE_TYPE} ${FILTER_MINIMUM} ${EVALUE} ${SEARCH_AND_ALIGN_ONLY} ${SEARCH_ONLY} ${EUK_CHECK} ${SEARCH_METHOD} ${MAXIMUM_RANGE} ${ASSIGNMENT_METHOD} ${PLACEMENTS_CUTOFF} ${RESOLVE_PLACEMENTS} ${NO_MERGE_READS} ${MIN_ORF_LENGTH} ${RESTRICT_READ_LENGTH} ${VERBOSITY} ${MAX_SAMPLES_FOR_KRONA}
